DjangoRestAPI/DjangoRestAPI/urls.py
from django.contrib import admin
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
import DjangoAPI.views as views


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path('events/', views.AllEventView.as_view()),
    path('events/<int:pk>/', views.EventDetailsView.as_view()),
    path('events/filter/', views.bootstrapFilterView, name='bootstrap')
    # re_path(r'(?P<pk>\d+)', django_views.UpdateView.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

DjangoRestAPI/DjangoAPI/models.py
from django.contrib.gis.db import models
from django.contrib.auth import get_user_model
# Create your models here.

STATUS_CHOICES = (
    ("Not Validated", "Not Validated"),
    ("Validated", "Validated"),
    ("Resolved", "Resolved")
)

EVENT_TYPE = (
    ('CONSTRUCTION', 'CONSTRUCTION'),
    ('SPECIAL_EVENT', 'SPECIAL_EVENT'),
    ('INCIDENT', 'INCIDENT'),
    ('WEATHER_CONDITION', 'WEATHER_CONDITION'),
    ('ROAD_CONDITION', 'ROAD_CONDITION')
)

User = get_user_model()

# Representation of an event


class Event(models.Model):
    Author = models.CharField(max_length=30)
    Location = models.PointField()
    CreationDate = models.DateField()
    ModDate = models.DateField()
    Description = models.CharField(max_length=100, default='Insert Description...')
    Status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Not Validated')
    EventType = models.CharField(max_length=20, choices=EVENT_TYPE, verbose_name="EVENT_TYPE")

    def __str__(self):
        return self.Author

DjangoRestAPI/DjangoAPI/forms.py
from django.forms import ModelForm
from .models import Event


def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)

# Form class for event type choice rendering in HTML
class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['EventType']

DjangoRestAPI/DjangoAPI/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.generics import ListAPIView
from .models import Event
from .serializer import EventSerializer
from django.shortcuts import render
from .forms import EventForm
from . import forms
# Create your views here.


# View that allows events to be filtered by author, location and type of event

def bootstrapFilterView(request):
    queryset = Event.objects.all()
    authorq = request.GET.get('author')
    locationq = request.GET.get('location')
    categoryq = request.GET.get('category')

    preset_form = forms.EventForm()

    if authorq != '' and authorq is not None:
        queryset = queryset.filter(Author__icontains=authorq)

    if locationq != '' and locationq is not None:
        queryset = queryset.filter(Location=locationq)

    if valid_param(categoryq) and categoryq != 'Choose...':
        queryset = queryset.filter(EventType__icontains=categoryq)

    context = {
        'queryset': queryset,
        'preset_form': preset_form
    }
    return render(request, "BootstrapFilter.html", context)


# Checks if an input parameter is valid

def valid_param(param):
    return param != '' and param is not None


# Allows viewing all the events that have been posted or create new ones

class AllEventView(ListAPIView):

    queryset = Event.objects.all()
    serializer_class = EventSerializer

    def post(self, request):
        serializer = EventSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


# Allows editing an event based on its id


class EventDetailsView(APIView):

    def get(self, request, pk):
        try:
            event = Event.objects.get(pk=pk)
            serializer = EventSerializer(event)
            return Response(serializer.data)
        except:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def delete(self, request, pk):
        event = Event.objects.get(pk=pk)
        event.delete()
        return Response(status=status.HTTP_200_OK)

    def put(self, request, pk):
        event = Event.objects.get(pk=pk)
        serializer = EventSerializer(event, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def patch(self, request, pk):
        event = Event.objects.get(pk=pk)
        serializer = EventSerializer(event, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

DjangoRestAPI/templates/BootstrapFilter.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Event Filter</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'template.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="#">Bootstrap</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#">React</a>
              </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">

      <h3>Event Filter</h3>
      <form method="GET" action=".">
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="author" placeholder="Author's name..." />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="location" placeholder="Location Coordinates..." />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4">
            <label for="category">Category</label>
            <select id="category" class="form-control" name="category">
              <option selected>Choose...</option>
              {% for cat in preset_form %}
              <option value={{ cat }}> {{ cat.get_EventType_display }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
      </form>

      <hr />

      <div class="row">
        <ul>
          {% for eve in queryset %}
            <li>
              <span>Author: {{ eve.Author }}</span>
              <span>Location: {{ eve.Location }}</span>
              <span>
                {% for cat in eve.EventType %}
                  {{ cat }}
                {% endfor %}
              </span>
            </li>
            <hr />
          {% endfor %}
        </ul>
      </div>

    </main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>

</html>